ContractSuite2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api', include('api.urls')),
    url(r'^settings/', include('settings.urls')),
    url(r'^form/', include('form.urls')),
    url(r'^geschaft/', include('geschaft.urls')),
    url(r'^projekt/folder', include('project_folder.urls')),
    url(r'^projekt/', include('projekt.urls')),
    url(r'^team/', include('team.urls')),
    url(r'^kanzlei/', include('kanzlei.urls')),
    url(r'^logout/', include('logout.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^terms/', include('terms.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'', include('index.urls')),
]

api/urls.py
from django.conf.urls import url
from . import views

app_name = 'api'

urlpatterns = [
    url(r'', views.api_dispatcher, name='api_dispatcher'),
]

geschaft/urls.py
from django.conf.urls import url
from . import views

app_name = 'geschaft'

urlpatterns = [
    url(r'(?P<geschaft_id>.+)$', views.geschaft_view, name='geschaft'),
]

project_folder/urls.py
from django.conf.urls import url
from . import views

app_name = 'project_folder'

urlpatterns = [
    url(r'/(?P<project_folder_id>.+)$', views.project_folder_detail_view, name='project_folder')
]

projekt/urls.py
from django.conf.urls import url
from . import views

app_name = 'projekt'

urlpatterns = [
    url(r'detail/(?P<projekt_id>.+)$', views.projekt_detail_view, name='projekt_detail'),
    url(r'', views.projekt_overview_view, name='projekt'),
]

project_folder/models.py
from django.db import models
from geschaft.models import Geschaft
from utils.utils import format_time

class ProjectFolder(models.Model):
    """
    A folder containing projects
    """
    #Name of the Folder
    name = models.CharField(max_length=100)

    parent_folder = models.ForeignKey("self", blank = True, null=True, related_name='parent_folder_set', on_delete=models.CASCADE)
    
    #auto_now_add makes an automatic timestamp when an instance is created
    created = models.DateTimeField(auto_now_add = True)
    #auto_now makes an automatic timestamp every time the instance is modified
    last_edited = models.DateTimeField(auto_now = True)
    
    def __str__(self):
        return self.name
    
    def list_parent_folders(self):
        folder_list = [self]
        folder = self
        while folder.parent_folder is not None:
            folder = folder.parent_folder
            folder_list.append(folder)
        return reversed(folder_list)
    
    
    def get_project(self):
        folder = self
        while folder.parent_folder is not None:
            folder = folder.parent_folder
        if folder.projekt is not None:
            return folder.projekt
        else:
            return None
    
    def str_created(self):
        return format_time(self.created)
    
    def str_last_edited(self):
        return format_time(self.last_edited)

    #Class method for creating new ProjektFolder
    @classmethod
    def create(cls, name, parent_folder = None):
        #Create ProjectFolder
        new_folder = cls(name = name, parent_folder = parent_folder)
        new_folder.save()
        
        #Return item for further use
        return new_folder

project_folder/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from projekt.models import Projekt
from .models import ProjectFolder
from geschaft.models import Geschaft
from template.models import Template, Container
from django.utils.timezone import utc
from utils.utils import custom_redirect
import datetime

def project_folder_detail_view(request, project_folder_id, container_id = False):
    """
    Redirects user to index if not authenticated, otherwise shows a project
    """
    #Redirect unauthenticated users
    if not request.user.is_authenticated:
        return redirect('index:index')
    
    #Check if user has accepted terms of use
    if not request.user.conventecuser.accepted_tou:
        return redirect('terms:terms')
    
    if request.user.conventecuser.kanzlei.deadline is not None and request.user.conventecuser.kanzlei.deadline <= datetime.datetime.now():
        return custom_redirect('login:error', e = 'deadline')
    
    project_folder = ProjectFolder.objects.get(id = project_folder_id)
    projekt = project_folder.get_project()
    
    #Check if user hase access
    has_access = False
    for team in request.user.conventecuser.teams.all():
        if team in projekt.teams.all():
            has_access = True
    
    try:
        if request.user.conventecuser.role == 'admin' and project_folder.get_project().teams.first().kanzlei == request.user.conventecuser.kanzlei:
            has_access = True
    except:
        pass
            
    if not has_access:
        return redirect('index:index')
    
    if request.method == 'GET':
        #Get sorted and reverse
        sorted_by = request.GET.get('sort', 'name')
        reverse = (request.GET.get('reverse', '') == 'true')
        
        container_id = request.GET.get('container', False)
        if container_id:
            container = Container.objects.get(id = int(container_id))
            parent_containers = container.list_parent_containers()
            
            if container.type == 'container':
                final_containers = sorted(container.container_set.all(), key=lambda x: x.name)
                final_templates = False
            else:
                final_containers = False
                final_templates = sorted(container.templates.all(), key=lambda x: x.name)
        else:
            
            container = False
            parent_containers = False
            final_containers = False
            final_templates = False
        
        if container and container.kanzleien.count() != 0 and not container.kanzleien.filter(id = request.user.conventecuser.kanzlei.id).exists():
            return redirect('index:index')
        
        
        #Provide context
        context = {
            'user' : request.user,
            'projekt' : projekt,
            'project_folder' : project_folder,
            'parent_folders' : project_folder.list_parent_folders(),
            'folders' : list_all_folders(project_folder, sorted_by, reverse),
            'geschafts' : list_all_geschafts(project_folder, sorted_by, reverse),
            'top_containers' : Container.get_top_containers(request.user),
            'container' : container,
            'final_containers' : final_containers,
            'final_templates' : final_templates,
            'parent_containers' : parent_containers,
            'active' : {'nav' : 'projekte', 'tabs' : 'ubersicht'}
                }
        
        return render(request, 'project_folder_view.html', context)
    
    elif request.method == 'POST':
        delete_folder = request.POST.get('delete_folder', False)
        delete_geschaft = request.POST.get('delete_geschaft', False)
        add_folder = request.POST.get('add_folder', False)
        
        add_geschaft = request.POST.get('add_geschaft', False)
        geschaft_name = request.POST.get('geschaft_name', None)
        
        if delete_folder:
            folder = ProjectFolder.objects.get(id = int(delete_folder))
            folder.delete()
            
        if delete_geschaft:
            geschaft = Geschaft.objects.get(id = int(delete_geschaft))
            geschaft.delete()
            
        if add_folder:
            ProjectFolder.create(add_folder, project_folder)
            
        if add_geschaft:
            template_temp = Template.objects.get(id = int(add_geschaft))
            if template_temp.kanzleien.count() == 0 or template_temp.kanzleien.filter(id = request.user.conventecuser.kanzlei.id).exists():
                Geschaft.create(int(add_geschaft), project_folder.id, geschaft_name)
            
        
        return redirect('project_folder:project_folder', project_folder.id)

def list_all_folders(project_folder, sorted_by, reverse):
    folders = project_folder.parent_folder_set.all()
    
    #Return sorted list
    if sorted_by == 'name':
        return sorted(folders, key=lambda x: x.name, reverse=reverse)
    elif sorted_by == 'created':
        return sorted(folders, key=lambda x: x.created, reverse=reverse)
    elif sorted_by == 'edited':
        return sorted(folders, key=lambda x: x.last_edited, reverse=reverse)
    else:
        return folders
    
def list_all_geschafts(project_folder, sorted_by, reverse):
    """
    Lists all geschafts of a given project_folder.
    """
    
    geschafts = project_folder.geschaft_set.all()
    
    #Return sorted list
    if sorted_by == 'name':
        return sorted(geschafts, key=lambda x: x.name, reverse=reverse)
    elif sorted_by == 'created':
        return sorted(geschafts, key=lambda x: x.created, reverse=reverse)
    elif sorted_by == 'edited':
        return sorted(geschafts, key=lambda x: x.last_edited, reverse=reverse)
    elif sorted_by == 'type':
        return sorted(geschafts, key=lambda x: x.template.name, reverse=reverse)
    else:
        return geschafts

project_folder/templates/project_folder_view.html
{% extends 'base.html' %}

{% block title %}
	Projekt {{ projekt.name }}
{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row" style="margin-top:50px;">
	  	<div class="col-md-10 col-md-offset-1">
	  		<ol class="breadcrumb" style="background-color:white;padding-left:0px;">
			  <li><a href="{% url 'projekt:projekt' %}">Projekte</a></li>
			  <li><a href="{% url 'project_folder:project_folder' project_folder_id=projekt.project_folder.id %}?active=ubersicht">{{ projekt.name }}</a></li>
			  <li><a href="{% url 'project_folder:project_folder' project_folder_id=projekt.project_folder.id %}?active=ubersicht">Übersicht</a></li>
			  {% for f in parent_folders %}
			  {% if not forloop.first %}
			  <li><a href="{% url 'project_folder:project_folder' project_folder_id=f.id %}?active=ubersicht">{{ f.name }}</a></li>
			  {% endif %}
			  {% endfor %}
			</ol>
	  	</div>
	</div>
	<div class="row" style="margin-top:10px;">
	  	<div class="col-md-10 col-md-offset-1">
	  		<h2>Projekt {{ projekt.name }}{% if projekt.completed %} (Abgeschlossen){% endif %}</h2>
	  		<p>{{ projekt.description }} </p>
	  		<p style="margin-top:30px;"><strong>Teams: </strong>{% for team in projekt.teams.all %}{{ team.name }}{% if team.id == projekt.lead.id%} (Lead){% endif %}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
	  	</div>
	</div>
	<div class="row" style="margin-top:30px;">
	  	<div class="col-md-10 col-md-offset-1">
	  		<ul class="nav nav-tabs">
  				<li {% if active.tabs == 'ubersicht' %}class="active"{% endif %}><a href="{% url 'project_folder:project_folder' project_folder_id=projekt.project_folder.id %}?active=ubersicht">Übersicht</a></li>
  				{% if not projekt.completed %}
  				{% if user.conventecuser.role == 'admin' or user.conventecuser.role == 'manager' %}
  				<li {% if active.tabs == 'bearbeiten' %}class="active"{% endif %}><a href="{% url 'projekt:projekt_detail' projekt_id=projekt.id %}?active=bearbeiten">Projekt bearbeiten</a></li>
  				<li {% if active.tabs == 'teams' %}class="active"{% endif %}><a href="{% url 'projekt:projekt_detail' projekt_id=projekt.id %}?active=teams">Teameinstellungen</a></li>
  				{% endif %}
  				{% endif %}
  				{% if user.conventecuser.role == 'admin' or user.conventecuser.role == 'manager' %}
  				<li {% if active.tabs == 'abschliessen' %}class="active"{% endif %}><a href="{% url 'projekt:projekt_detail' projekt_id=projekt.id %}?active=abschliessen">Projekt {% if not projekt.completed %}abschliessen{% else %}aktivieren{% endif %}</a></li>
  				<li {% if active.tabs == 'loschen' %}class="active"{% endif %}><a href="{% url 'projekt:projekt_detail' projekt_id=projekt.id %}?active=loschen">Projekt löschen</a></li>
  				{% endif %}
			</ul>
	  	</div>
	</div>
	<div class="row" style="margin-top:50px;">
		<div class="col-md-10 col-md-offset-1">
			<h4 id="folder-title">{{ project_folder.name }}</h4>
		</div>
	</div>
	<div class="row" style="margin-top:10px;">
  		<div class="col-md-10 col-md-offset-1" style="margin-top:30px;">
  			<div class="table-responsive">
  				<table class="table table-hover" data-link="row">
					<thead>
      					<tr>
      						<th></th>
        					<th>Name <a href="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}?active={{active.tabs}}&sort=name&reverse=false#folder-title"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></a><a href="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}?active={{active.tabs}}&sort=name&reverse=true#folder-title"></span><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></a></th>
        					<th>Typ <a href="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}?active={{active.tabs}}&sort=type&reverse=false#folder-title"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></a><a href="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}?active={{active.tabs}}&sort=type&reverse=true#folder-title"></span><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></a></th>
        					<th>Erstellt <a href="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}?active={{active.tabs}}&sort=created&reverse=false#folder-title"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></a><a href="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}?active={{active.tabs}}&sort=created&reverse=true#folder-title"></span><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></a></th>
        					<th>Zuletzt bearbeitet <a href="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}?active={{active.tabs}}&sort=edited&reverse=false#folder-title"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></a><a href="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}?active={{active.tabs}}&sort=edited&reverse=true#folder-title"></span><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></a></th>
        					<th>Löschen</th>
      					</tr>
    				</thead>
    				<tbody>
    					{% for folder in folders %}
    						<tr style="cursor:pointer;">
    							<td><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span></td>
        						<td><a href="{% url 'project_folder:project_folder' project_folder_id=folder.id %}#folder-title"></a><strong>{{ folder.name }}</strong></td>
        						<td>Ordner</td>
        						<td>{{ folder.str_created }}</td>
        						<td>{{ folder.str_last_edited }}</td>
        						<td><form action="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}" method="post">{% csrf_token %}<input type="hidden" name="delete_folder" value="{{ folder.id }}"><button type='submit' class='btn btn-danger delete-folder'><span class='glyphicon glyphicon-remove' aria-hidden='false'></span></button></form></td>
      						</tr>
						{% endfor %}
    					{% for geschaft in geschafts %}
    						<tr style="cursor:pointer;">
    							<td><span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span></td>
        						<td><a href="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}"></a><strong>{{ geschaft.name }}</strong></td>
        						<td>{{ geschaft.template.name }}</td>
        						<td>{{ geschaft.str_created }}</td>
        						<td>{{ geschaft.str_last_edited }}</td>
        						<td><form action="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}" method="post">{% csrf_token %}<input type="hidden" name="delete_geschaft" value="{{ geschaft.id }}"><button type='submit' class='btn btn-danger delete-geschaft'><span class='glyphicon glyphicon-remove' aria-hidden='false'></span></button></form></td>
      						</tr>
						{% endfor %}
    				</tbody>
  				</table>
			</div>
  		</div>
	</div>
	<script>
		var folders = document.getElementsByClassName('delete-folder');
		for(var i = 0; i < folders.length; i++){
			folders[i].addEventListener('click', function(e){
				e.preventDefault();
				e.stopPropagation();
			    if(confirm('Wollen Sie den Ordner und alle Inhalte endgültig löschen?')){
			    	e.target.parentElement.submit();
			    }
			})
		}
		var geschafts = document.getElementsByClassName('delete-geschaft');
		for(var i = 0; i < geschafts.length; i++){
			geschafts[i].addEventListener('click', function(e){
				e.preventDefault();
				e.stopPropagation();
			    if(confirm('Wollen Sie das Geschäft endgültig löschen?')){
			    	e.target.parentElement.submit();
			    }
			})
		}
	</script>
	{% if not projekt.completed %}
	<div class="row" style="margin-top:50px;margin-bottom:30px;cursor:pointer;">
		<div class="col-md-10 col-md-offset-1">
			{% if project_folder.parent_folder %}
			<a href="{% url 'project_folder:project_folder' project_folder_id=project_folder.parent_folder.id %}#folder-title"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>Zurück</a>
			{% endif %}
		</div>
	</div>
	<div class="row" style="cursor:pointer;margin-top:50px;">
		<div class="col-md-10 col-md-offset-1">
			<form action="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}" method="post">
				<div class="input-group" style="max-width:500px;">
					{% csrf_token %}
					<input type="text" name="add_folder" class="form-control" placeholder="Name">
					<span class="input-group-btn">
				    	<button type='submit' class='btn btn-success'>Ordner hinzufügen</button></form>
				    </span>
	    		</div>
	    	</form>
		</div>
	</div>
	<div class="row" style="cursor:pointer;margin-top:50px;">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-primary" style="min-height:300px;">
				<div class="panel-heading">
					<p>Geschäft hinzufügen</p>
				</div>
  				<div class="panel-body" id="geschaft-selection">
  					<ul class="nav nav-pills nav-stacked" style="max-width:200px;display:inline-block;vertical-align:top;">
  						{% for t_container in top_containers %}
						<li {% if container and t_container.id == container.id %}class="active"{% endif %}><a href="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}?container={{ t_container.id }}#geschaft-selection">{{ t_container.name }}</a></li>
						{% endfor %}
					</ul>
					{% if parent_containers %}
					{% for p_container in parent_containers %}
					{% if not forloop.first %}
					<ul class="nav nav-pills nav-stacked" style="max-width:200px;display:inline-block;vertical-align:top;">
						<li {% if container and p_container.id == container.id %}class="active"{% endif %}><a href="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}?container={{ p_container.id }}#geschaft-selection">{{ p_container.name }}</a></li>
					</ul>
					{% endif %}
					{% endfor %}
					{% endif %}
					{% if final_containers %}
					<ul class="nav nav-pills nav-stacked" style="max-width:200px;display:inline-block;vertical-align:top;">
					{% for f_container in final_containers %}
						<li><a href="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}?container={{ f_container.id }}#geschaft-selection">{{ f_container.name }}</a></li>
					{% endfor %}
					</ul>
					{% endif %}
					{% if final_templates %}
					<ul class="nav nav-pills nav-stacked" style="max-width:500px;display:inline-block;vertical-align:top;">
					{% for template in final_templates %}
						<li><a class="geschaft-click" data-template-id="{{ template.id }}">{{ template.name }}</a></li>
					{% endfor %}
					</ul>
					{% endif %}
					<form id="add-geschaft-form" action="{% url 'project_folder:project_folder' project_folder_id=project_folder.id %}" method="post" style="margin-top:50px;display:none;">
					<div class="input-group" style="max-width:500px;">
						{% csrf_token %}
						<input id="input-template-id" type="hidden" name="add_geschaft" value="" class="form-control" placeholder="Name">
						<input type="text" name="geschaft_name" value="" class="form-control" placeholder="Name">
						<span class="input-group-btn">
					    	<button type='submit' class='btn btn-success'>Geschäft hinzufügen</button></form>
					    </span>
		    		</div>
	    	</form>
  				</div>
			</div>
		</div>
	</div>
	<script>
	var geschafts = document.getElementsByClassName('geschaft-click');
	for(var i = 0; i < geschafts.length; i++){
		geschafts[i].addEventListener('click', function(e){
			var form = document.getElementById('add-geschaft-form');
			form.style.display = 'block';
			document.getElementById('input-template-id').value = e.target.getAttribute('data-template-id');
			var geschafts = document.getElementsByClassName('geschaft-click');
			for(var i = 0; i < geschafts.length; i++){
				geschafts[i].parentElement.setAttribute("class", "");
			}
			e.target.parentElement.setAttribute("class", "active");
		})
	}
	</script>
	{% endif %}
</div>
{% endblock %}