ContractSuite2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api', include('api.urls')),
    url(r'^settings/', include('settings.urls')),
    url(r'^form/', include('form.urls')),
    url(r'^geschaft/', include('geschaft.urls')),
    url(r'^projekt/folder', include('project_folder.urls')),
    url(r'^projekt/', include('projekt.urls')),
    url(r'^team/', include('team.urls')),
    url(r'^kanzlei/', include('kanzlei.urls')),
    url(r'^logout/', include('logout.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^terms/', include('terms.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'', include('index.urls')),
]

api/urls.py
from django.conf.urls import url
from . import views

app_name = 'api'

urlpatterns = [
    url(r'', views.api_dispatcher, name='api_dispatcher'),
]

form/urls.py
from django.conf.urls import url
from . import views

app_name = 'form'

urlpatterns = [
    url(r'', views.form_view, name='form'),
]

geschaft/urls.py
from django.conf.urls import url
from . import views

app_name = 'geschaft'

urlpatterns = [
    url(r'(?P<geschaft_id>.+)$', views.geschaft_view, name='geschaft'),
]

project_folder/urls.py
from django.conf.urls import url
from . import views

app_name = 'project_folder'

urlpatterns = [
    url(r'/(?P<project_folder_id>.+)$', views.project_folder_detail_view, name='project_folder')
]

projekt/urls.py
from django.conf.urls import url
from . import views

app_name = 'projekt'

urlpatterns = [
    url(r'detail/(?P<projekt_id>.+)$', views.projekt_detail_view, name='projekt_detail'),
    url(r'', views.projekt_overview_view, name='projekt'),
]

geschaft/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from utils.utils import format_time

class Geschaft(models.Model):
    """
    A Geschaft within a Projekt Folder
    """
    #Name of the Geschaft
    name = models.CharField(max_length=100)
    
    #auto_now_add makes an automatic timestamp when an instance is created
    created = models.DateTimeField(auto_now_add = True)
    #auto_now makes an automatic timestamp every time the instance is modified
    last_edited = models.DateTimeField(auto_now = True)
    
    #The template
    template = models.ForeignKey("template.Template", on_delete=models.PROTECT)
    
    #The project folder
    project_folder = models.ForeignKey("project_folder.ProjectFolder", on_delete=models.CASCADE)
    
    #The variables
    variables = JSONField(default="{}")
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Geschäft"
        verbose_name_plural = "Geschäfte"
        
    def str_created(self):
        return format_time(self.created)
    
    def str_last_edited(self):
        return format_time(self.last_edited)
    
    def get_project(self):
        return self.project_folder.get_project()
    
    def download_all(self):
        return self.template.download_all(self.id)
    
    #Class method for creating new Geschaft
    @classmethod
    def create(cls, template_id, project_folder_id, geschaft_name = None):
        from template.models import Template
        from project_folder.models import ProjectFolder
        
        template = Template.objects.get(id = template_id)
        project_folder = ProjectFolder.objects.get(id = project_folder_id)
        
        if geschaft_name is None:
            geschaft_name = template.name
        
        #Create Geschaft
        new_geschaft = cls(name = geschaft_name, template = template, project_folder = project_folder)
        
        new_geschaft.save()
        
        #Return item for further use
        return new_geschaft

geschaft/views.py
from django.shortcuts import render, redirect
from .models import Geschaft
from document.models import Document
from project_folder.models import ProjectFolder
from utils.utils import custom_redirect
from django.utils.timezone import utc
import datetime
from django.conf import settings

def geschaft_view(request, geschaft_id):
    """
    Redirects user to index if not authenticated, otherwise shows a geschaft
    """
     
    #Redirect unauthenticated users
    if not request.user.is_authenticated:
        return redirect('index:index')
    
    #Check if user has accepted terms of use
    if not request.user.conventecuser.accepted_tou:
        return redirect('terms:terms')
    
    if request.user.conventecuser.kanzlei.deadline is not None and request.user.conventecuser.kanzlei.deadline <= datetime.datetime.now():
        return custom_redirect('login:error', e = 'deadline')
    
    geschaft = Geschaft.objects.get(id = geschaft_id)
    
    #Check if user hase access
    has_access = False
    for team in request.user.conventecuser.teams.all():
        for project in team.projekt_set.all():
            if geschaft.project_folder.get_project() == project:
                has_access = True
                
    try:
        if request.user.conventecuser.role == 'admin' and geschaft.project_folder.get_project().teams.first().kanzlei == request.user.conventecuser.kanzlei:
            has_access = True
    except:
        pass
            
    if not has_access:
        return redirect('index:index')
    
    if request.method == 'GET':
        #Get sorted and reverse
        sorted_by = request.GET.get('sort', 'name')
        reverse = (request.GET.get('reverse', '') == 'true')
        
        #Get active tab
        active = request.GET.get('active', 'formular')

        #Get success
        success = request.GET.get('success', 'false')
        
        #Get error
        error = request.GET.get('e', 'false')
        
        #Provide context
        context = {
            'error' : error,
            'user' : request.user,
            'geschaft'    : geschaft,
            'projekt' : geschaft.get_project(),
            'parent_folders' : geschaft.project_folder.list_parent_folders(),
            'documents' : list_all_documents(geschaft, sorted_by, reverse),
            'active' : {'nav' : 'projekte', 'tabs' : active},
            'success' : success
                }
        
        return render(request, 'geschaft.html', context)
    
    elif request.method == 'POST':
        
        #Get POST data
        #Get active tab
        active = request.POST.get('active', 'dokumente')
        
        name = request.POST.get('name', False)
        loschen = request.POST.get('loschen', False)
        
        document_id = request.POST.get('document_id', False)
        all = request.POST.get('all', False)
        
        variables = request.POST.get('variables', False)
        
        folder = request.POST.get('folder', False)
        
        if name:
            geschaft.name = name
            geschaft.save()
        
        if loschen:
            project_folder_id = geschaft.project_folder.get_project().id
            geschaft.delete()
            return redirect('project_folder:project_folder', project_folder_id = project_folder_id)
        
        if geschaft_id and document_id:
            document = Document.objects.get(id = document_id)
            
            if settings.DEBUG:
                download = document.download(geschaft_id)
                
                if download:
                    return download
                else:
                    return custom_redirect('geschaft:geschaft', geschaft_id, e = 'true', active = 'dokumente')
            
            else:
                try:
                    download = document.download(geschaft_id)
                
                    if download:
                        return download
                    else:
                        return custom_redirect('geschaft:geschaft', geschaft_id, e = 'true', active = 'dokumente')
                except:
                    return custom_redirect('geschaft:geschaft', geschaft_id, e = 'true', active = 'dokumente')
            
        if geschaft_id and all:
            if settings.DEBUG:
                return geschaft.download_all()
            else:
                try:
                    return geschaft.download_all()
                except:
                    return custom_redirect('geschaft:geschaft', geschaft_id, e = 'true', active = 'dokumente')
            
        if variables:
            geschaft.variables = variables
            geschaft.save()
            return custom_redirect('geschaft:geschaft', geschaft_id, active = 'ubersicht')
        
        if folder:
            geschaft.project_folder = ProjectFolder.objects.get(id = int(folder))
            geschaft.save()
            
        
        #Provide context
        context = {
            'user' : request.user,
            'geschaft' : geschaft,
            'projekt' : geschaft.get_project(),
            'active' : {'nav' : 'projekte', 'tabs' : active},
            'success' : 'true'
                }
        
        return render(request, 'geschaft.html', context)
    
def list_all_documents(geschaft, sorted_by, reverse):
    """
    Lists all documents of a given template (if they are required).
    List can be sorted by: name.
    """
    from jinja2 import Template
    import json
    
    documents = geschaft.template.documents.all()
    displayed_documents = []
    
    for document in documents:
        if document.display_condition is not None:
            template = Template(document.display_condition)

            try:
                if template.render(json.loads(geschaft.variables)) == 'true':
                    displayed_documents.append(document)
            except:
                pass
        else:
            displayed_documents.append(document)
    
    #Return sorted list
    if sorted_by == 'name':
        return sorted(displayed_documents, key=lambda x: x.name, reverse=reverse)
    else:
        return displayed_documents

geschaft/templates/geschaft.html
{% extends 'base.html' %}

{% block title %}
	Geschäft {{ geschaft.name }}
{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row" style="margin-top:50px;">
	  	<div class="col-md-10 col-md-offset-1">
	  		<ol class="breadcrumb" style="background-color:white;padding-left:0px;">
			  <li><a href="{% url 'projekt:projekt' %}">Projekte</a></li>
			  {% for f in parent_folders %}
			  <li><a href="{% url 'project_folder:project_folder' project_folder_id=f.id %}?active=ubersicht">{{ f.name }}</a></li>
			  {% endfor %}
			  <li><a href="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}?active=formular">{{ geschaft.name }}</a></li>
			  {% if active.tabs == 'formular' %}
			  <li><a href="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}?active=formular">Formular</a></li>
			  {% elif active.tabs == 'dokumente' %}
			  <li><a href="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}?active=dokumente">Dokumente</a></li>
			  {% elif active.tabs == 'bearbeiten' %}
			  <li><a href="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}?active=bearbeiten">Einstellungen</a></li>
			  {% elif active.tabs == 'loschen' %}
			  <li><a href="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}?active=loschen">Geschäft löschen</a></li>
			  {% endif %}
			</ol>
	  	</div>
	</div>
	<div class="row" style="margin-top:10px;">
	  	<div class="col-md-10 col-md-offset-1">
	  		<h2>Geschäft {{ geschaft.name }}</h2>
	  		{% if geschaft.project.completed %}<p><i>Das Projekt dieses Geschäfts wurde abgeschlossen. Aktivieren sie das Projekt zur bearbeitung dieses Geschäfts.</i></p>{% endif %}
	  		<p style="margin-top:30px;"><strong>Projekt: </strong><a href="{% url 'projekt:projekt_detail' projekt_id=projekt.id %}">{{ geschaft.project_folder.get_project }}</a></p>
	  	</div>
	</div>
	<div class="row" style="margin-top:30px;">
	  	<div class="col-md-10 col-md-offset-1">
	  		<ul class="nav nav-tabs">
	  			{% if not geschaft.project.completed %}
	  			<li {% if active.tabs == 'formular' %}class="active"{% endif %}><a href="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}?active=formular">Formular</a></li>
	  			{% endif %}
  				<li {% if active.tabs == 'dokumente' %}class="active"{% endif %}><a href="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}?active=dokumente">Dokumente</a></li>
  				{% if not geschaft.project.completed %}
  				<li {% if active.tabs == 'bearbeiten' %}class="active"{% endif %}><a href="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}?active=bearbeiten">Einstellungen</a></li>
  				{% endif %}
  				<li {% if active.tabs == 'loschen' %}class="active"{% endif %}><a href="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}?active=loschen">Geschäft löschen</a></li>
			</ul>
	  	</div>
	</div>
	{% if active.tabs == 'dokumente' %}
	<div class="row" style="margin-top:50px;">
		<div class="col-md-10 col-md-offset-1">
			<h4>Dokumente</h4>
		</div>
  		<div class="col-md-10 col-md-offset-1" style="margin-top:30px;">
  			<table class="table table-hover">
				<thead>
      				<tr>
        				<th>Name <a href="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}?active={{active.tabs}}&sort=name&reverse=false"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></a><a href="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}?active={{active.tabs}}&sort=name&reverse=true"></span><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></a></th>
        				<th>Download</th>
      				</tr>
    			</thead>
    			<tbody>
    				{% for document in documents %}
    					<tr>
        					<td>{{ document.name }}</td>
        					<td><form method="post" action="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}">{% csrf_token %}<input type="hidden" name="geschaft_id" value="{{ geschaft.id }}"/><input type="hidden" name="document_id" value="{{ document.id }}"/><button type="submit" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></button></form></td>
      					</tr>
					{% endfor %}
					<tr>
        				<td><strong>Alle Dokumente als zip File</strong></td>
        				<td><form method="post" action="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}">{% csrf_token %}<input type="hidden" name="geschaft_id" value="{{ geschaft.id }}"/><input type="hidden" name="all" value="true"/><button type="submit" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span></button></form></td>
      				</tr>
    			</tbody>
  			</table>
  		</div>
	</div>
	{% if error == 'true' %}
	<script>
		alert("Es ist ein Fehler augetreten, bitte überprüfen Sie das Formular.");
	</script>
	{% endif %}
	{% elif active.tabs == 'formular' %}
  	<div class="row" style="margin-top:50px;">
  		<div class="col-md-10 col-md-offset-1">
  			<h4>Formular</h4>
  			<form method="post" action="{% url 'form:form' %}" style="margin-top:30px;">{% csrf_token %}<input type="hidden" name="geschaft_id" value="{{ geschaft.id }}"/><button type="submit" class="btn btn-sm btn-primary">Formular bearbeiten</button></form>
  		</div>
  	</div>
	{% elif active.tabs == 'bearbeiten' and success == 'false' %}
	<div class="row" style="margin-top:50px;">
  		<div class="col-md-10 col-md-offset-1">
  			<h4>Einstellungen</h4>
  			<form action="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}" method="post" style="margin-top:30px;">
  				{% csrf_token %}
  				<div class="form-group">
  					<label>Name:</label>
  					<input type="text" class="form-control" name="name" value="{{ geschaft.name }}" style="max-width:500px;">
				</div>
				<div class="form-group">
					<label style="max-width:500px;text-align:justify;">Ordner</label>
					<select class="form-control" name="folder" style="max-width:100px;">
    					{% for folder in geschaft.project_folder.get_project.list_all_folders %}
    					<option value="{{ folder.id }}" {% if folder.id == geschaft.project_folder.id %}selected="selected"{% endif %}>{{ folder.name }}</option>
    					{% endfor %}
  					</select>
				</div>
				<input type="hidden" name="active" value="{{ active.tabs }}">
				<button type="submit" class="btn btn-primary" style="margin-top:30px;margin-bottom:30px;">Ändern</button>
  			</form>
  		</div>
  	</div>
  	{% elif active.tabs == 'loschen' and success == 'false' %}
  	<div class="row" style="margin-top:50px;">
  		<div class="col-md-10 col-md-offset-1">
  			<h4>Löschen</h4>
  			<form action="{% url 'geschaft:geschaft' geschaft_id=geschaft.id %}" method="post" style="margin-top:30px;">
  				{% csrf_token %}
  				<input type="hidden" name="loschen" value="true">
  				<input type="hidden" name="active" value="{{ active.tabs }}">
				<button type="submit" class="btn btn-primary" style="margin-top:30px;margin-bottom:30px;" onclick="delete_geschaft(event);">Geschäft löschen</button>
  			</form>
  		</div>
  	</div>
	{% else %}
	<div class="row" style="margin-top:50px;">
  		<div class="col-md-10 col-md-offset-1">
  			<div class="alert alert-success">
			 	Geschäft erfolgreich bearbeitet.
			</div>
  		</div>
	</div>
	{% endif %}
</div>
<script>
function delete_geschaft(e) {
	if(confirm("Wollen Sie das Geschäft unwiderruflich löschen?")){
	}
	else{
		e.preventDefault();
	}
}
</script>
{% endblock %}