ContractSuite2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api', include('api.urls')),
    url(r'^settings/', include('settings.urls')),
    url(r'^form/', include('form.urls')),
    url(r'^geschaft/', include('geschaft.urls')),
    url(r'^projekt/folder', include('project_folder.urls')),
    url(r'^projekt/', include('projekt.urls')),
    url(r'^team/', include('team.urls')),
    url(r'^kanzlei/', include('kanzlei.urls')),
    url(r'^logout/', include('logout.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^terms/', include('terms.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'', include('index.urls')),
]

api/urls.py
from django.conf.urls import url
from . import views

app_name = 'api'

urlpatterns = [
    url(r'', views.api_dispatcher, name='api_dispatcher'),
]

kanzlei/urls.py
from django.conf.urls import url
from . import views

app_name = 'kanzlei'

urlpatterns = [
    url(r'(?P<kanzlei_id>.+)/user/(?P<user_id>.+)$', views.kanzlei_user_detail, name='kanzlei_user_detail'),
    url(r'(?P<kanzlei_id>.+)/user$', views.kanzlei_user, name='kanzlei_user'),
    url(r'(?P<kanzlei_id>.+)$', views.kanzlei_view, name='kanzlei')
]

kanzlei/models.py
from django.db import models
    

class Kanzlei(models.Model):
    """
    Extending the default Django user model
    """
    #Name of the kanzlei
    name = models.CharField(max_length=100)
    
    #Deadline when the kanzlei expires
    deadline = models.DateTimeField(default=None, blank=True, null = True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Kanzlei"
        verbose_name_plural = "Kanzleien"

team/models.py
from django.db import models
from kanzlei.models import Kanzlei

class Team(models.Model):
    """
    A Team of a Kanzlei
    """
    #Name of the kanzlei
    name = models.CharField(max_length=100)
    
    #Description of the team
    description = models.TextField(max_length=3000)
    
    #Kanzlei of the Team
    kanzlei = models.ForeignKey(Kanzlei, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.kanzlei.name + ' - ' + self.name
    
    class Meta:
        verbose_name = "Team"
        verbose_name_plural = "Teams"
        
    @classmethod
    def create(cls, name, description, kanzlei):
        
        #Create Team
        new_team = cls(name = name, description = description, kanzlei = kanzlei)
        
        new_team.save()
        
        #Return team for further use
        return new_team
    
    

kanzlei/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.utils.timezone import utc
from utils.utils import custom_redirect
import datetime

from .models import Kanzlei
from login.models import ConventecUser

from django.contrib.auth.models import User

def kanzlei_view(request, kanzlei_id):
    """
    Redirects user to if not authenticated, otherwise shows kanzlei view
    """
     
    #Redirect unauthenticated users
    if not request.user.is_authenticated:
        return redirect('index:index')
    
    #Check if user has accepted terms of use
    if not request.user.conventecuser.accepted_tou:
        return redirect('terms:terms')
    
    if request.user.conventecuser.kanzlei.deadline is not None and request.user.conventecuser.kanzlei.deadline <= datetime.datetime.now():
        return custom_redirect('login:error', e = 'deadline')
    
    #Check if user is admin
    if not request.user.conventecuser.role == 'admin':
            return redirect('index:index')
    
    #Get Kanzlei
    kanzlei = Kanzlei.objects.get(id = int(kanzlei_id))
    
    #Redirect if user not in kanzlei
    if request.user.conventecuser.kanzlei.id != kanzlei.id:
        return redirect('index:index')

    
    #Provide name of user and items the user has access to
    context = {
        'user' : request.user,
        'active' : {'nav' : 'kanzlei'}
            }
    
    return render(request, 'kanzlei.html', context)

def kanzlei_user(request, kanzlei_id):
    """
    Redirects user to if not authenticated, otherwise shows users of kanzlei
    """
     
    #Redirect unauthenticated users
    if not request.user.is_authenticated:
        return redirect('index:index')
    
    #Check if user has accepted terms of use
    if not request.user.conventecuser.accepted_tou:
        return redirect('terms:terms')
    
    #Get Kanzlei
    kanzlei = Kanzlei.objects.get(id = kanzlei_id)
    
    #Redirect if user not in kanzlei
    if request.user.conventecuser.kanzlei.id != kanzlei.id:
        return redirect('index:index')
    
    if request.method == 'GET':
        #Get sorted and reverse
        sorted_by = request.GET.get('sort', 'l_name')
        reverse = (request.GET.get('reverse', '') == 'true')
        
        vorname = request.GET.get('vorname', '')
        nachname = request.GET.get('nachname', '')
        email = request.GET.get('email', '')
        position = request.GET.get('position', '')
        role = request.GET.get('role', '')
        
        e = request.GET.get('e', False)

    
        #Provide name of user and items the user has access to
        context = {
            'user' : request.user,
            'kanzlei' : request.user.conventecuser.kanzlei,
            'members' : list_all_members(request, sorted_by, reverse),
            'active' : {'nav' : 'kanzlei'},
            'vorname' : vorname,
            'nachname' : nachname,
            'email' : email,
            'position' :position,
            'role' : role,
            'e' : e
                }
        
        return render(request, 'kanzlei_user.html', context)
    
    elif request.method == 'POST':
        if not request.user.conventecuser.role == 'admin':
            return redirect('index:index')
        
        vorname = request.POST.get('vorname', False)
        nachname = request.POST.get('nachname', False)
        email = request.POST.get('email', False)
        position = request.POST.get('position', False)
        role = request.POST.get('role', False)
        pw1 = request.POST.get('pw1', False)
        pw2 = request.POST.get('pw2', False)
        
        remove = request.POST.get('remove', False)
        
        if vorname and nachname and email and position and role and pw1 and pw2 and pw1 == pw2:
            # Check if email is already taken

            try:
                user = User.objects.get(email = email)
                return custom_redirect('kanzlei:kanzlei_user', kanzlei.id, e = 'email', vorname = vorname, nachname = nachname, position = position, role = role, scroll_to = 'erstellen')
            except User.DoesNotExist:
                pass
            
            new_user = ConventecUser.create(vorname, nachname, email, position, role, pw1, kanzlei)
        
        if remove:
            user = User.objects.get(id = int(remove))
            if user.conventecuser.kanzlei.id == kanzlei.id:
                user.delete()
                
        return redirect('kanzlei:kanzlei_user', kanzlei.id)
    
def kanzlei_user_detail(request, kanzlei_id, user_id):
    """
    Redirects user to if not authenticated, otherwise shows users of kanzlei
    """
     
    #Redirect unauthenticated users
    if not request.user.is_authenticated:
        return redirect('index:index')
    
    #Check if user has accepted terms of use
    if not request.user.conventecuser.accepted_tou:
        return redirect('terms:terms')
    
    #Get Kanzlei
    kanzlei = Kanzlei.objects.get(id = int(kanzlei_id))
    
    #Get User
    user = User.objects.get(id = int(user_id))
    
    #Redirect if user not in kanzlei
    if request.user.conventecuser.kanzlei.id != kanzlei.id or user.conventecuser.kanzlei.id != kanzlei.id:
        return redirect('index:index')
    
    if request.method == 'GET':
        
        s = request.GET.get('s', False)

        #Provide name of user and items the user has access to
        context = {
            'user' : user,
            'kanzlei' : request.user.conventecuser.kanzlei,
            'active' : {'nav' : 'kanzlei'},
            's' : s
                }
        
        return render(request, 'kanzlei_user_detail.html', context)
    
    elif request.method == 'POST':
        
        vorname = request.POST.get('vorname', False)
        nachname = request.POST.get('nachname', False)
        email = request.POST.get('email', False)
        position = request.POST.get('position', False)
        role = request.POST.get('role', False)
        pw1 = request.POST.get('pw1', False)
        pw2 = request.POST.get('pw2', False)
        
        if vorname:
            user.first_name = vorname
            user.save()
            
        if nachname:
            user.last_name = nachname
            user.save()
            
        if email:
            if email != user.email:
                try:
                    user = User.objects.get(email = email)
                    return custom_redirect('kanzlei:kanzlei_user_detail', kanzlei.id, user.id, s = 'fail', scroll_to = 'bearbeiten')
                except User.DoesNotExist:
                    pass
            user.email = email
            user.save()
            
        if pw1 and pw2 and pw1 == pw2:
            user.set_password(pw1)
            user.save()
            
        if position:
            user.conventecuser.position = position
            user.conventecuser.save()
            
        if role:
            user.conventecuser.role = role
            user.conventecuser.save()
        
                
        return custom_redirect('kanzlei:kanzlei_user_detail', kanzlei.id, user.id, s = 'success', scroll_to = 'bearbeiten')

def list_all_members(request, sorted_by, reverse):
    """
    Lists all users of a kanzlei.
    List can be sorted by: name, role, position.
    """
    users = request.user.conventecuser.kanzlei.conventecuser_set.all()
    
    #Return sorted list
    if sorted_by == 'f_name':
        return sorted(users, key=lambda x: x.user.first_name, reverse=reverse)
    elif sorted_by == 'l_name':
        return sorted(users, key=lambda x: x.user.last_name, reverse=reverse)
    elif sorted_by == 'position':
        return sorted(users, key=lambda x: x.position, reverse=reverse)
    elif sorted_by == 'role':
        return sorted(users, key=lambda x: x.role, reverse=reverse)
    else:
        return users

kanzlei/templates/kanzlei.html
{% extends 'base.html' %}

{% block title %}
	Kanzlei
{% endblock %}

{% block static %}
	{% load staticfiles %}
	<script src="{% static 'core/jquery/jquery.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'core/bootstrap/css/bootstrap.min.css' %}" />
	<script src="{% static 'core/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'core/jasny-bootstrap/js/jasny-bootstrap.min.js' %}"></script>
{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row" style="margin-top:50px;">
	  	<div class="col-md-10 col-md-offset-1">
	  		<ol class="breadcrumb" style="background-color:white;padding-left:0px;">
			  <li><a href="{% url 'kanzlei:kanzlei' kanzlei_id=user.conventecuser.kanzlei.id %}">Kanzlei</a></li>
			</ol>
	  	</div>
	</div>
	<div class="row" style="margin-top:10px;">
	  	<div class="col-md-10 col-md-offset-1">
	  		<h2>{{ user.conventecuser.kanzlei.name }}</h2>
	  		<h4>{{ user.conventecuser.kanzlei.conventecuser_set.all | length }}{% if user.conventecuser.kanzlei.conventecuser_set.all|length > 1 %} Users {% else %} User {% endif %}in {{ user.conventecuser.kanzlei.team_set.all | length }}{% if user.conventecuser.kanzlei.team_set.all|length > 1 %} Teams {% else %} Team{% endif %} </h4>
	  		{% if user.conventecuser.role == 'admin' %}
	  		<a class="btn btn-primary" href="{% url 'kanzlei:kanzlei_user' kanzlei_id=user.conventecuser.kanzlei.id %}" style="margin-top:30px;">User Management</a>
	  		{% endif %}
	  	</div>
	</div>
	<div class="row" style="margin-top:50px;">
  		<div class="col-md-10 col-md-offset-1">
  			<table class="table table-hover" data-link="row">
				<thead>
      				<tr>
        				<th>Team Name</th>
        				<th>Beschreibung</th>
        				<th>Mitglieder</th>
        
      				</tr>
    			</thead>
    			<tbody>
    				{% for team in user.conventecuser.kanzlei.team_set.all %}
    					<tr>
        					<td><strong>{{ team.name }}</strong></td>
        					<td>{{ team.description }}</td>
        					<td>{% for mitglied in team.conventecuser_set.all %}{{ mitglied.user.get_full_name }}{% if mitglied.position %} ({{ mitglied.position }}){% endif %}<br/>{% endfor %}</td>
      					</tr>
					{% endfor %}
    			</tbody>
  			</table>
  		</div>
	</div>
</div>
{% endblock %}

kanzlei/templates/kanzlei_user.html
{% extends 'base.html' %}

{% block title %}
	Kanzlei {{ kanzlei.name }}
{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row" style="margin-top:50px;">
	  	<div class="col-md-10 col-md-offset-1">
	  		<ol class="breadcrumb" style="background-color:white;padding-left:0px;">
			  <li><a href="{% url 'kanzlei:kanzlei' kanzlei_id=kanzlei.id %}">Kanzlei</a></li>
			  <li><a href="{% url 'kanzlei:kanzlei_user' kanzlei_id=kanzlei.id %}">User Management</a></li>
			</ol>
	  	</div>
	</div>
	<div class="row" style="margin-top:50px;margin-bottom:50px;">
		<div class="col-md-10 col-md-offset-1">
			<h2>Kanzleimitarbeiter</h2>
		</div>
  		<div class="col-md-10 col-md-offset-1" style="margin-top:30px;">
  				<table class="table table-hover" id="table-users">
					<thead>
      					<tr>
      						<th>Nachname<a href="{% url 'kanzlei:kanzlei_user' kanzlei_id=kanzlei.id %}?sort=l_name&reverse=false#table-users"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></a><a href="{% url 'kanzlei:kanzlei_user' kanzlei_id=kanzlei.id %}?sort=l_name&reverse=true#table-users"></span><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></a></th>
        					<th>Vorname<a href="{% url 'kanzlei:kanzlei_user' kanzlei_id=kanzlei.id %}?sort=f_name&reverse=false#table-users"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></a><a href="{% url 'kanzlei:kanzlei_user' kanzlei_id=kanzlei.id %}?sort=f_name&reverse=true#table-users"></span><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></a></th>
        					<th>Position<a href="{% url 'kanzlei:kanzlei_user' kanzlei_id=kanzlei.id %}?sort=position&reverse=false#table-users"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></a><a href="{% url 'kanzlei:kanzlei_user' kanzlei_id=kanzlei.id %}?sort=type&reverse=true#table-users"></span><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></a></th>
        					<th>Rolle <a href="{% url 'kanzlei:kanzlei_user' kanzlei_id=kanzlei.id %}?sort=role&reverse=false#table-users"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></a><a href="{% url 'kanzlei:kanzlei_user' kanzlei_id=kanzlei.id %}?sort=created&reverse=true#table-users"></span><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></a></th>
        					<th>Mitarbeiter Bearbeiten</th>
        					<th>Mitarbeiter Löschen</th>
      					</tr>
    				</thead>
    				<tbody>
    					{% for member in members %}
    						<tr>
    							<td>{{ member.user.last_name }}</td>
        						<td>{{ member.user.first_name }}</td>
        						<td>{{ member.position }}</td>
        						<td>{{ member.get_role_display }}</td>
        						<td><a href="{% url 'kanzlei:kanzlei_user_detail' kanzlei_id=kanzlei.id user_id=member.user.id %}" class="btn btn-info" role="button"><span class='glyphicon glyphicon-pencil' aria-hidden='false'></span></a>
        						<td>{% if not user.id == member.user.id %}<form action="{% url 'kanzlei:kanzlei_user' kanzlei_id=kanzlei.id %}#table-users" method="post">{% csrf_token %}<input type="hidden" name="remove" value="{{ member.user.id }}"><button type='submit' class='btn btn-danger' onclick="delete_user(event);"><span class='glyphicon glyphicon-remove' aria-hidden='false'></span></button></form>{% else %}Sie können sich selbst nicht löschen.{% endif %}</td>
      						</tr>
						{% endfor %}
    				</tbody>
  				</table>
  		</div>
	</div>
	<div class="row" style="margin-top:50px;">
  		<div class="col-md-10 col-md-offset-1">
  			<h3 id="erstellen">Mitarbeiter hinzufügen</h3>
  			{% if e %}
  			<div class="alert alert-danger" role="alert" style="max-width:500px;">
  				{% if e == 'email' %}Diese E-Mail Adresse wird bereits verwendet{% endif %}
			</div>
			{% endif %}
  			<form action="{% url 'kanzlei:kanzlei_user' kanzlei_id=kanzlei.id %}" method="post" style="margin-top:30px;">
  				{% csrf_token %}
  				<div class="form-group">
  					<label>Vorname:</label>
  					<input type="text" class="form-control" id="vorname" name="vorname" value="{% if vorname %}{{ vorname }}{% endif %}" style="max-width:500px;">
				</div>
				<div class="form-group">
  					<label>Nachname:</label>
  					<input type="text" class="form-control" id="nachname" name="nachname" value="{% if nachname %}{{ nachname }}{% endif %}" style="max-width:500px;">
				</div> 
				<div class="form-group">
  					<label>Email:</label>
  					<input type="text" class="form-control" id="email" name="email" value="{% if email %}{{ email }}{% endif %}" style="max-width:500px;">
				</div> 
				<div class="form-group">
  					<label>Position:</label>
  					<input type="text" class="form-control" id="position" name="position" value="{% if position %}{{ position }}{% endif %}" style="max-width:500px;">
				</div> 
				<div class="form-group">
					<label>Rolle:</label>
				 	<select class="form-control" id="role" name="role" value="{% if role %}{{ role }}{% endif %}" style="max-width:500px;">
				    	<option value="admin">Kanzlei Admin</option>
				    	<option value="manager">Projektmanager</option>
				    	<option value="mitarbeiter">Projektmitarbeiter</option>
				 	</select>
				</div> 
				<div class="form-group">
  					<label>Passwort:</label>
  					<input type="password" class="form-control" id="pw1" name="pw1" style="max-width:500px;">
				</div> 
				<div class="form-group">
  					<label>Passwort wiederholen:</label>
  					<input type="password" class="form-control" id="pw2" name="pw2" style="max-width:500px;">
				</div>
				<button type="submit" onclick="check_entries(event)" class="btn btn-primary" style="margin-top:30px;margin-bottom:30px;">User erstellen</button>
  			</form>
  		</div>
	</div>
	<script>
  	function delete_user(e) {
  		if(confirm("Wollen Sie den User unwiderruflich löschen?")){
  		}
  		else{
  			e.preventDefault();
  		}
  	}
	function check_entries(e){
		vorname = document.getElementById('vorname');
		nachname = document.getElementById('nachname');
		email = document.getElementById('email');
		position = document.getElementById('position');
		role = document.getElementById('role');
		pw1 = document.getElementById('pw1');
		pw2 = document.getElementById('pw2');
		
		if( typeof vorname.value == 'undefined' || typeof nachname.value == 'undefined' || typeof email.value == 'undefined' || typeof position.value == 'undefined' || typeof role.value == 'undefined' || typeof pw1.value == 'undefined' || typeof pw2.value == 'undefined' || vorname.value == '' || nachname.value == '' || email.value == '' || position.value == '' || role.value == '' || pw1.value == '' || pw2.value == ''){
			alert('Der User wird nur erstellt wenn das ganze Formular ausgefüllt wurde.');
			e.preventDefault();
		}
		
		else if(pw1.value != pw2.value){
			alert('Die Passwörter stimmen nicht überein.');
			e.preventDefault();
		}
	}
  	</script>
</div>
{% endblock %}

kanzlei/templates/kanzlei_user_detail.html
{% extends 'base.html' %}

{% block title %}
	Kanzlei {{ kanzlei.name }}
{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row" style="margin-top:50px;">
	  	<div class="col-md-10 col-md-offset-1">
	  		<ol class="breadcrumb" style="background-color:white;padding-left:0px;">
			  <li><a href="{% url 'kanzlei:kanzlei' kanzlei_id=kanzlei.id %}">Kanzlei</a></li>
			  <li><a href="{% url 'kanzlei:kanzlei_user' kanzlei_id=kanzlei.id %}">User Management</a></li>
			  <li><a href="{% url 'kanzlei:kanzlei_user_detail' kanzlei_id=kanzlei.id user_id=user.id %}">{{ user.get_full_name }}</a></li>
			</ol>
	  	</div>
	</div>
	<div class="row" style="margin-top:50px;">
  		<div class="col-md-10 col-md-offset-1">
  			<h3 id="bearbeiten">Mitarbeiter bearbeiten</h3>
  			{% if s %}
  			<div class="alert alert-{% if s == 'success' %}success{% else %}danger{% endif %}" role="alert" style="max-width:500px;">
  				{% if s == 'success' %}Der User wurde erfolgreich bearbeitet{% elif s == 'fail' %}Die E-Mail konnte nicht geändert werden, da sie bereits in verwendung ist{% endif %}
			</div>
			{% endif %}
  			<form action="{% url 'kanzlei:kanzlei_user_detail' kanzlei_id=kanzlei.id user_id=user.id %}" method="post" style="margin-top:30px;">
  				{% csrf_token %}
  				<div class="form-group">
  					<label>Vorname:</label>
  					<input type="text" class="form-control" value="{{ user.first_name }}" name="vorname" style="max-width:500px;">
				</div>
				<div class="form-group">
  					<label>Nachname:</label>
  					<input type="text" class="form-control" value="{{ user.last_name }}" name="nachname" style="max-width:500px;">
				</div> 
				<div class="form-group">
  					<label>Email:</label>
  					<input type="text" class="form-control" value="{{ user.email }}" name="email" style="max-width:500px;">
				</div> 
				<div class="form-group">
  					<label>Position:</label>
  					<input type="text" class="form-control" value="{{ user.conventecuser.position }}" name="position" style="max-width:500px;">
				</div> 
				<div class="form-group">
					<label>Rolle:</label>
				 	<select class="form-control" name="role" style="max-width:500px;">
				    	<option value="admin" {% if user.conventecuser.role == 'admin' %}selected="selected"{% endif %}>Kanzlei Admin</option>
				    	<option value="manager" {% if user.conventecuser.role == 'manager' %}selected="selected"{% endif %}>Projektmanager</option>
				    	<option value="mitarbeiter" {% if user.conventecuser.role == 'mitarbeiter' %}selected="selected"{% endif %}>Projektmitarbeiter</option>
				 	</select>
				</div> 
				<div class="form-group">
  					<label>Passwort:</label>
  					<input type="password" class="form-control" id="pw1" name="pw1" style="max-width:500px;" placeholder="Optional">
				</div> 
				<div class="form-group">
  					<label>Passwort wiederholen:</label>
  					<input type="password" class="form-control" id="pw2" name="pw2" style="max-width:500px;" placeholder="Optional">
				</div>
				<button type="submit" onclick="check_entries(event)" class="btn btn-primary" style="margin-top:30px;margin-bottom:30px;">Änderungen speichern</button>
  			</form>
  		</div>
  		<div class="row" style="margin-top:50px;margin-bottom:50px;">
  			<div class="col-md-10 col-md-offset-1">
  				<a href="{% url 'kanzlei:kanzlei_user'  kanzlei.id %}" style="margin-bottom:50px;margin-top:20px;"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Zurück</a>
	  		</div>
	  	</div>
	</div>
	<script>
		function check_entries(e){
			pw1 = document.getElementById('pw1');
			pw2 = document.getElementById('pw2');
			if(typeof pw1.value != 'undefined' && typeof pw2.value != 'undefined' && (pw1.value != '' || pw2.value != '') && (pw1.value != pw2.value)){
				alert('Die Passwörter stimmen nicht überein.');
				e.preventDefault();
			}
		}
	</script>
</div>
{% endblock %}